name = "ivanramirez-git"
main = "src/worker.js"
compatibility_date = "2026-02-12"

[assets]
directory = "./dist"
binding = "ASSETS"

[[routes]]
pattern = "platano.ivanrene.com/*"
zone_name = "ivanrene.com"
